### ISSUE TITLE
Reference letter 

### ISSUE THREAD

**Issue by xiaoiker** [razvanmarinescu/EB1A#12]
Hi, really a nice material for the DIY application, thanks a lot! 

I have a question about the reference letter. You mentioned that "Reference letter writers should also ideally not be in your immediate collaborator circle". So you are saying better not to ask reference letter from your co-authors, right? Even he is very famous in the field? 

Any tools to strategy to find these persons? 

BTW, I read your StyleGAN3D paper, which is a nice baseline. 

Thanks 
Wei

**Comment by razvanmarinescu** [comment]
Yes, ideally not in your immediate collaborator circle. You can still have some from (former) advisors and collaborators, but try to include as many "independents" as you can. Good luck!

**Comment by xiaoiker** [comment]
Thanks for the prompt response.
