### ISSUE TITLE
Proof scientic reviews

### ISSUE THREAD

**Issue by xiaoiker** [razvanmarinescu/EB1A#13]
Thanks again for your previous response. I think better to open a new issue for others to check as well.

My question is what should be the proof of scientic reviews? The inviation email? For Journals, we do have such emails. But how about for conferences?, e.g., CVPR. Normally, the invitation is not specific to one article, and you can be assgined for several papers. So what should be the proof for that? 

Thanks.

**Comment by razvanmarinescu** [comment]
I attached confirmation emails that my review was received in their system. You generally get those, including for CVPR, and even contain the full review that you wrote.
