### ISSUE TITLE
Is the Statement your petition letter?

### ISSUE THREAD

**Issue by siddhantekale** [razvanmarinescu/EB1A#2]
If it is, wanted to know why you kept it short (its really good!), just don't know what the USCIS expects

**Comment by razvanmarinescu** [comment]
There's no requirement/advice I can give on the length. You need to answer properly to all the criteria, but if you can do it in a short document, that is all fine.

**Comment by razvanmarinescu** [comment]
Don't know what you mean by statement. The main application document is in main.pdf

**Comment by siddhantekale** [comment]
Got it, Makes sense that this is case by case! Did you have a cover letter in addition to this?

**Comment by siddhantekale** [comment]
Razvan's pdf is a complete application including the cover letter.

**Comment by razvanmarinescu** [comment]
Yes, you can add an additional cover letter if you think that will help.
