### ISSUE TITLE
Who did you consult with for your I-485 step?

### ISSUE THREAD

**Issue by siddhantekale** [razvanmarinescu/EB1A#3]
Hey Razvan,

I have a lot to thank you for, but I'll do that in a blog post soon. I wanted to check who you used for your I-485 application? Trying to beat a priority date so seeing who is available at the earliest.

Best,
Siddhant

**Comment by razvanmarinescu** [comment]
Hi Siddhant! You mean the lawyer? It was Yaming Gao: http://www.lawyergao.com/englishversion/aboutus.html

If you mean the processing center, I used National Benefits Center.

**Comment by siddhantekale** [comment]
Thank you! Will reach out to Yaming Gao. Appreciate your prompt response!
