### ISSUE TITLE
EB-2 NIW

### ISSUE THREAD

**Issue by sherani87** [razvanmarinescu/EB1A#4]
Hi Razvan
I saw your blog and you did a great job. I have a question. As i have below qualifications.

Master Degree in Computer Science
4 years Work Experience
Currently working as Senior Cloud Engineer. (US faces a very heavy shortage in Cloud Engineer)
Publication: Don't have but Currently working on 1 Research.

Am I eligible for EB2 NIW. as most of the lawyers they refuse to take my case.

Thanks

**Comment by razvanmarinescu** [comment]
It's a hard one. You need to satisfy at least 2 of the 8-10 criteria for NIW, plus make a case for why your work as a cloud engineer is in the national interest of the US. Do you have any leadership, or did you judge the work of others? You have to think about it and realize whether you can do it or not.  

You can also try to make an effort over the next couple years to satisfy some of those, then apply for it.
