### ISSUE TITLE
Bio for recommenders

### ISSUE THREAD

**Issue by liecn** [razvanmarinescu/EB1A#7]
Hello Razvan,

Thank you very much for providing all this information.

I have a question: Regarding the bios of the recommenders you attached, are they brief bios (around one page) or the first page of their resumes? I already have the full resumes for these recommenders, which are over 10 pages each.

Thanks,
Chenning

**Comment by razvanmarinescu** [comment]
Mine were brief, 1-2 pages. But up to you, not a big deal if a few are longer
